#!/bin/bash -e
#@author Aleksandar Gotev (alex.gotev@mobimesh.it)

. config.conf

BASE_FOLDER=$(pwd)

PJSIP_BASE_PATH="${BASE_FOLDER}/${PJSIP_DIR_NAME}"
PJSIP_TMP_PATH="/tmp/pjsip"
CONFIG_SITE_PATH="${PJSIP_BASE_PATH}/pjlib/include/pj/config_site.h"
PJSUA_BASE_DIR="${PJSIP_TMP_PATH}/pjsip-apps/src/swig"
PJSUA_GENERATED_SRC_DIR="${PJSUA_BASE_DIR}/java/android/app/src/main/java"
PJSUA_GENERATED_SO_PATH="${PJSUA_BASE_DIR}/java/android/app/src/main/jniLibs/armeabi/libpjsua2.so"
FINAL_BUILD_DIR="${BASE_FOLDER}/pjsip-build"
FINAL_BUILD_LIB="${FINAL_BUILD_DIR}/lib"
FINAL_BUILD_LOGS="${FINAL_BUILD_DIR}/logs"
LIBOPUS_PATH="${PJSIP_BASE_PATH}/pjmedia/include/pjmedia-codec/libopus"

export ANDROID_NDK_ROOT="${NDK_PATH}"
export PATH="$ANDROID_NDK_ROOT:$PATH"

echo "Clear final build folder ..."
rm -rf "${FINAL_BUILD_DIR}"
mkdir -p "${FINAL_BUILD_LIB}"
mkdir -p "${FINAL_BUILD_LOGS}"

echo "Creating config site file for Android ..."
cat <<EOF > "$CONFIG_SITE_PATH"
#define PJ_CONFIG_ANDROID 1
#include <pj/config_site_sample.h>
#define PJMEDIA_HAS_VIDEO 0
#define PJMEDIA_HAS_OPUS_CODEC 1
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_HAS_SPEEX_CODEC 0
#define PJMEDIA_HAS_ILBC_CODEC 0
#define PJMEDIA_HAS_G722_CODEC 0
#define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 1
#define PJMEDIA_AUDIO_DEV_HAS_OPENSL 0	
#define PJSIP_TRANSPORT_IDLE_TIME 60000
#define PJSIP_TD_TIMEOUT 3200000
#define PJSIP_HAS_TLS_TRANSPORT 1
EOF

for arch in "${TARGET_ARCHS[@]}"
do
    echo "Compile PJSIP for arch $arch ..."
    rm -rf "${PJSIP_TMP_PATH}"
    mkdir -p "${PJSIP_TMP_PATH}"
    cd "${PJSIP_BASE_PATH}"
    cp -r * "${PJSIP_TMP_PATH}"
    cd "${PJSIP_TMP_PATH}"

    rm -rf "${LIBOPUS_PATH}"
    mkdir -p "${LIBOPUS_PATH}"
    cp -r "${OPUS_BUILD_OUT_PATH}/${arch}/include/opus/." "${LIBOPUS_PATH}"

    APP_PLATFORM=android-${TARGET_ANDROID_API} NDK_TOOLCHAIN_VERSION=4.9 TARGET_ABI=$arch ./configure-android --use-ndk-cflags \
                                         --with-ssl="${OPENSSL_BUILD_OUT_PATH}/libs/${arch}" \
                                         --with-opus="${OPUS_BUILD_OUT_PATH}/${arch}"
                                         >>"${FINAL_BUILD_LOGS}/${arch}.log" 2>&1
    make dep >>"${FINAL_BUILD_LOGS}/${arch}.log" 2>&1
    make >>"${FINAL_BUILD_LOGS}/${arch}.log" 2>&1

    echo "Compile PJSUA for arch $arch ..."
    cd "${PJSUA_BASE_DIR}"
    make >>"${FINAL_BUILD_LOGS}/${arch}.log" 2>&1

    echo "Copying PJSUA .so library to final build directory ..."
    mkdir -p "${FINAL_BUILD_LIB}/${arch}"
    mv "${PJSUA_GENERATED_SO_PATH}" "${FINAL_BUILD_LIB}/${arch}/"

done

echo "Copying PJSUA2 java bindings to final build directory ..."
cp -r "${PJSUA_GENERATED_SRC_DIR}" "${FINAL_BUILD_DIR}"
rm -rf "${PJSIP_TMP_PATH}"
echo "Finished! Check the generated output in ${FINAL_BUILD_DIR}"
