#!/bin/bash -e

. config.conf

echo "Building opus..."

mkdir -p "${OPUS_DIR_NAME}/jni"
cp -r Android.mk "${OPUS_DIR_NAME}/jni/Android.mk"
cp -r Application.mk "${OPUS_DIR_NAME}/jni/Application.mk"
cd "$OPUS_DIR_NAME"
"${NDK_PATH}/ndk-build"
cd ..

rm -rf "$OPUS_BUILD_OUT_PATH"

for arch in "${TARGET_ARCHS[@]}"
do
	mkdir -p "${OPUS_BUILD_OUT_PATH}/${arch}/include/opus"
	mkdir -p "${OPUS_BUILD_OUT_PATH}/${arch}/lib"
	cp -r "${OPUS_DIR_NAME}/include/." "${OPUS_BUILD_OUT_PATH}/${arch}/include/opus/"
	cp -r "${OPUS_DIR_NAME}/obj/local/${arch}/libopus.a" "${OPUS_BUILD_OUT_PATH}/${arch}/lib/libopus.a"
done